"""
Inserisce le risposte della sezione Artificial Intelligence (R197-R205)
nel file Pirelli compilato da Marco, mantenendo il pattern narrativo esistente
(ISO 27001:2022 come ancora, maiuscolo, Partial+improvement).
"""
import openpyxl
from openpyxl.styles import Alignment, Font
from copy import copy

SRC = '/home/claude/pirelli_165.xlsx'
OUT = '/mnt/user-data/outputs/SECXLS_Pirelli_NOLOOP_AI_section_filled.xlsx'

# Risposte (answer, description) per ciascuna riga della sezione AI
# Riga 197 = intestazione del dominio (no answer richiesto)
answers = {}

# R198 — Pirelli Data
answers[198] = (
    "Partial",
    """NOLOOP DOES NOT CURRENTLY PROCESS PIRELLI DATA THROUGH ARTIFICIAL INTELLIGENCE SERVICES WITHIN THE SCOPE OF THE SERVICES PROVIDED TO PIRELLI (EVENTS ORGANIZATION).

NOLOOP HAS DEVELOPED AND OPERATES AI-ENABLED TOOLS THAT MAY POTENTIALLY BE EXTENDED TO PIRELLI SERVICES IN THE FUTURE, SUBJECT TO AGREEMENT WITH PIRELLI. THESE INCLUDE: (I) AN EVENTS MANAGEMENT PLATFORM WITH AN INTEGRATED AI ASSISTANT FOR SECRETARIAT AUTOMATION (INVITATIONS, PARTICIPANTS COMMUNICATIONS, LOGISTICS); (II) AN AI-BASED MEETING TRANSCRIPTION AND SUMMARY TOOL; (III) SUPPORTING AI SOLUTIONS FOR INTERNAL PRODUCTIVITY (SCOUTING, CRM, KNOWLEDGE BASE).

SHOULD AI TECHNOLOGIES BE APPLIED TO PIRELLI DATA IN THE FUTURE, THE TYPES OF DATA POTENTIALLY PROCESSED WOULD BE LIMITED TO: PARTICIPANT DATA (NAME, SURNAME, EMAIL, LOGISTICS PREFERENCES) FOR EVENT SECRETARIAT AUTOMATION, AND MEETING TRANSCRIPTIONS. PROCESSING WOULD BE PERFORMED ON NOLOOP-CONTROLLED INFRASTRUCTURE WITH THE SAME SECURITY AND PRIVACY CONTROLS APPLIED TO NON-AI PROCESSING OF PIRELLI DATA DESCRIBED ELSEWHERE IN THIS ASSESSMENT."""
)

# R199 — Information Security Policy and Procedures (AI)
answers[199] = (
    "Yes",
    """NOLOOP HAS ESTABLISHED, APPROVED AND MAINTAINS AN INTERNAL POLICY AND REGISTER FOR ARTIFICIAL INTELLIGENCE (R71 REGISTER OF AUTHORIZED ARTIFICIAL INTELLIGENCE SOLUTIONS), AS PART OF ITS INTEGRATED MANAGEMENT SYSTEM, ISO/IEC 27001:2022 CERTIFIED INFORMATION SECURITY MANAGEMENT SYSTEM AND GDPR/PRIVACY GOVERNANCE FRAMEWORK.

THE REGISTER DOCUMENTS, FOR EACH AUTHORIZED AI SOLUTION: SUPPLIER/PLATFORM, VERSION/ENVIRONMENT, APPROVED PURPOSES OF USE, EU AI ACT RISK CATEGORY, AUTHORIZED PROCESSES AND ROLES, ALLOWED DATA CATEGORIES AND LIMITATIONS, AND THE APPLICABLE SECURITY AND PRIVACY REQUIREMENTS (TRAINING ON NOLOOP DATA DISABLED, MEMORY/HISTORY LIMITATION, RETENTION CONFIGURATION, ENCRYPTION IN TRANSIT AND AT REST, ACCESS WITH NOLOOP ACCOUNT AND MFA, AUDIT LOGS, DPIA/PRIVACY ASSESSMENT WHERE APPLICABLE, CONTRACTUAL DPA WITH THE PROVIDER).

THE REGISTER COVERS BOTH AUTHORIZED THIRD-PARTY AI SERVICES (E.G. ENTERPRISE GENERATIVE AI ASSISTANTS, MICROSOFT 365 COPILOT, MICROSOFT TEAMS TRANSCRIPTION) AND CUSTOM AI SOLUTIONS DEVELOPED ON NOLOOP INFRASTRUCTURE. POLICIES ARE ALIGNED WITH EU AI ACT PRINCIPLES (CURRENTLY LIMITED-RISK CATEGORY FOR AUTHORIZED SOLUTIONS), GDPR REQUIREMENTS AND INFORMATION SECURITY CONTROLS.

THE INDEX OF THE APPLICABLE POLICY AND REGISTER CAN BE SHARED WITH PIRELLI SUBJECT TO CONFIDENTIALITY AND DOCUMENT CONTROL REQUIREMENTS."""
)

# R200 — Data quality and assurance
answers[200] = (
    "Yes",
    """NOLOOP ENSURES DATA INTEGRITY ACROSS THE LIFECYCLE OF AI SYSTEMS THROUGH TECHNICAL, ORGANIZATIONAL AND PROCEDURAL CONTROLS DEFINED WITHIN ITS INTEGRATED MANAGEMENT SYSTEM, ISO/IEC 27001:2022 CERTIFIED INFORMATION SECURITY MANAGEMENT SYSTEM AND GDPR/PRIVACY GOVERNANCE FRAMEWORK.

A) DATA LIFECYCLE MANAGEMENT AVAILABLE TO PIRELLI: WHERE AI IS APPLIED TO PIRELLI DATA, DATA IS MANAGED ACCORDING TO PIRELLI'S INSTRUCTIONS AND CONTRACTUAL REQUIREMENTS. PIRELLI CAN EXERCISE RIGHTS OF ACCESS, RECTIFICATION, DELETION AND RESTRICTION OVER ITS DATA CONSISTENTLY WITH GDPR AND THE APPLICABLE AGREEMENTS. RETENTION PERIODS FOLLOW CONTRACTUAL AND REGULATORY REQUIREMENTS.

B) ACCURACY OF AI-DRIVEN OUTPUTS AND DATA QUALITY ASSURANCE: AI OUTPUTS ARE SUBJECT TO HUMAN SUPERVISION AND VALIDATION BEFORE OPERATIONAL USE. AI OUTPUTS ARE NOT USED AS THE SOLE BASIS FOR AUTOMATED DECISIONS PRODUCING LEGAL OR SIMILARLY SIGNIFICANT EFFECTS ON DATA SUBJECTS. NOLOOP DOES NOT TRAIN OR FINE-TUNE AI MODELS ON PIRELLI DATA. AI-DRIVEN FUNCTIONALITIES IN NOLOOP CUSTOM SOLUTIONS LEVERAGE PRE-TRAINED ENTERPRISE-GRADE LANGUAGE MODELS ACCESSED VIA API INVOCATIONS ORCHESTRATED BY THE NOLOOP APPLICATION BACKEND, THROUGH ENTERPRISE-GRADE MODEL PROVIDERS (ANTHROPIC, OPENAI, GOOGLE GEMINI, ACCESSED VIA THE OPENROUTER AGGREGATOR), CONFIGURED WITH TRAINING OPT-OUT AND NO PROVIDER-SIDE RETENTION.

C) TRUSTED DATA SOURCES: INPUT DATA FOR AI SYSTEMS COMES EXCLUSIVELY FROM AUTHORIZED NOLOOP SYSTEMS OR AUTHORIZED CUSTOMER-PROVIDED SOURCES, PROCESSED ON NOLOOP-CONTROLLED INFRASTRUCTURE. NO DATA IS ACQUIRED FROM UNTRUSTED OR PUBLIC SOURCES FOR AI PROCESSING OF CUSTOMER DATA."""
)

# R201 — Pirelli data not retained by AI services
answers[201] = (
    "Yes",
    """NOLOOP CONFIRMS THAT PIRELLI DATA, WHERE PROCESSED THROUGH ARTIFICIAL INTELLIGENCE SERVICES, IS NOT RETAINED BY THE AI TECHNOLOGY PROVIDERS AND IS NOT USED TO TRAIN OR FINE-TUNE THE UNDERLYING LANGUAGE MODELS.

AI-DRIVEN FUNCTIONALITIES IN NOLOOP CUSTOM SOLUTIONS INVOKE LARGE LANGUAGE MODELS VIA API CALLS ORCHESTRATED BY THE NOLOOP APPLICATION BACKEND. API CALLS ARE ROUTED THROUGH THE OPENROUTER AGGREGATOR, WHICH PROVIDES ACCESS TO ENTERPRISE-GRADE MODEL PROVIDERS (ANTHROPIC, OPENAI, GOOGLE GEMINI). API INVOCATIONS ARE CONFIGURED IN LINE WITH ENTERPRISE-GRADE TERMS WHICH PROVIDE FOR TRAINING OPT-OUT AND NO PROVIDER-SIDE RETENTION OF SUBMITTED DATA.

PIRELLI DATA, WHERE PROCESSED BY AI FUNCTIONALITIES, RESIDES ON NOLOOP-CONTROLLED PHYSICAL INFRASTRUCTURE, WITH THE PRIMARY SERVER ENVIRONMENT LOCATED IN MILAN AND A SECONDARY BACKUP/DISASTER RECOVERY SITE LOCATED IN ROME, CONSISTENTLY WITH WHAT DESCRIBED IN THE DATA SECURITY AND PRIVACY LIFECYCLE MANAGEMENT AND DATACENTER SECURITY SECTIONS OF THIS ASSESSMENT.

RETENTION OF PIRELLI DATA ON NOLOOP SYSTEMS FOLLOWS CONTRACTUAL, GDPR AND INTERNAL RETENTION REQUIREMENTS, WITH SECURE DELETION UPON PIRELLI'S REQUEST OR UPON EXPIRY OF THE DEFINED RETENTION PERIOD."""
)

# R202 — Anonymization/pseudonymization
answers[202] = (
    "Partial",
    """NOLOOP APPLIES DATA MINIMIZATION AND PURPOSE LIMITATION PRINCIPLES WITHIN ITS GDPR/PRIVACY GOVERNANCE FRAMEWORK AND ISO/IEC 27001:2022 CERTIFIED INFORMATION SECURITY MANAGEMENT SYSTEM. FOR AI-DRIVEN PROCESSING, ONLY THE DATA STRICTLY NECESSARY FOR THE SPECIFIC FUNCTIONALITY IS SUBMITTED TO AI SERVICES.

WHERE APPLICABLE, PSEUDONYMIZATION OR ANONYMIZATION TECHNIQUES CAN BE APPLIED TO PERSONAL DATA BEFORE AI PROCESSING, ACCORDING TO THE PURPOSE OF THE PROCESSING AND CONTRACTUAL REQUIREMENTS. EXAMPLES INCLUDE REMOVAL OR MASKING OF DIRECT IDENTIFIERS FROM TRANSCRIPTIONS INTENDED FOR ANALYTICAL OR STATISTICAL PURPOSES, AGGREGATION OF PARTICIPANT DATA FOR STATISTICAL OUTPUTS, AND EXCLUSION OF SENSITIVE ATTRIBUTES NOT REQUIRED BY THE FUNCTIONALITY.

THE SOFTWARE ARCHITECTURE SUPPORTS: (I) DATA MINIMIZATION, THROUGH SUBMISSION TO AI CALLS OF ONLY THE NECESSARY DATA FIELDS; (II) STORAGE LIMITATION, WITH NO RETENTION BY AI PROVIDERS AND NOLOOP-SIDE RETENTION LIMITED TO CONTRACTUAL AND REGULATORY REQUIREMENTS; (III) PRIVACY RIGHTS (ACCESS, RECTIFICATION, ERASURE) ACCORDING TO GDPR, WITHOUT COMPROMISING AI PERFORMANCE.

HOWEVER, THE FORMALIZATION OF A DEDICATED, AI-SPECIFIC ANONYMIZATION AND PSEUDONYMIZATION PROCEDURE IS CURRENTLY UNDER EVALUATION AS AN IMPROVEMENT ACTION OF NOLOOP'S INFORMATION SECURITY MANAGEMENT SYSTEM."""
)

# R203 — Model training security (anti model-inversion, anti data-poisoning)
answers[203] = (
    "Partial",
    """NOLOOP DOES NOT TRAIN OR FINE-TUNE AI LANGUAGE MODELS USING CUSTOMER DATA, INCLUDING PIRELLI DATA. AI FUNCTIONALITIES IN NOLOOP SOLUTIONS LEVERAGE PRE-TRAINED ENTERPRISE-GRADE LANGUAGE MODELS PROVIDED BY THIRD-PARTY PROVIDERS (ANTHROPIC, OPENAI, GOOGLE GEMINI), ACCESSED VIA THE OPENROUTER AGGREGATOR AND INVOKED THROUGH API CALLS ORCHESTRATED BY THE NOLOOP APPLICATION BACKEND. API CALLS ARE CONFIGURED WITH TRAINING OPT-OUT AND NO PROVIDER-SIDE RETENTION.

A) RISK OF MODEL INVERSION ATTACKS AND EXPOSURE OF SENSITIVE OR COPYRIGHTED INFORMATION DURING TRAINING: SINCE NOLOOP DOES NOT PERFORM TRAINING OR FINE-TUNING OF LANGUAGE MODELS, INTERNAL EXPOSURE OF SENSITIVE OR COPYRIGHTED DATA THROUGH TRAINING PROCESSES IS NOT APPLICABLE. MITIGATION OF MODEL INVERSION RISKS AT THE UNDERLYING MODEL LEVEL RELIES ON THE ENTERPRISE PROVIDERS, WHOSE CONTRACTUAL TERMS GUARANTEE THAT API-SUBMITTED DATA IS NOT USED TO TRAIN SHARED MODELS. AT PROMPT LEVEL, NOLOOP APPLIES DATA MINIMIZATION PRINCIPLES TO REDUCE INADVERTENT EXPOSURE OF SENSITIVE INFORMATION.

B) PROTECTION AGAINST DATA POISONING AND UNAUTHORIZED ACCESS TO TRAINING DATA: SINCE NOLOOP DOES NOT MANAGE TRAINING DATASETS OF AI MODELS, THERE IS NO NOLOOP-MANAGED TRAINING DATASET POTENTIALLY SUBJECT TO DATA POISONING. ACCESS TO AI SYSTEMS, TO THE DATA PROCESSED BY AI AND TO THE APPLICATION BACKEND INVOKING AI APIS IS RESTRICTED TO AUTHORIZED PERSONNEL AND MANAGED ACCORDING TO NOLOOP ACCESS MANAGEMENT, INFORMATION SECURITY, ENDPOINT SECURITY AND CHANGE MANAGEMENT PROCEDURES. AI-RELATED USAGE IS LOGGED AT APPLICATION LEVEL AND MONITORED FOR ANOMALIES.

HOWEVER, THE FORMALIZATION OF A STANDALONE AI-SPECIFIC SECURITY POLICY SPECIFICALLY COVERING MODEL TRAINING AND ADVERSARIAL-AI RISKS IS CURRENTLY UNDER EVALUATION AS AN IMPROVEMENT ACTION OF NOLOOP'S INFORMATION SECURITY MANAGEMENT SYSTEM."""
)

# R204 — Encryption
answers[204] = (
    "Yes",
    """NOLOOP ENSURES THE SECURE STORAGE OF DATA, INCLUDING DATA PROCESSED BY AI SYSTEMS, THROUGH APPROPRIATE ENCRYPTION MECHANISMS AND ACCESS CONTROLS, AS DESCRIBED IN THE CRYPTOGRAPHY, ENCRYPTION & KEY MANAGEMENT AND DATA SECURITY AND PRIVACY LIFECYCLE MANAGEMENT SECTIONS OF THIS ASSESSMENT.

DATA PROCESSED BY AI SYSTEMS RESIDES ON NOLOOP-CONTROLLED PHYSICAL INFRASTRUCTURE, WITH THE PRIMARY SERVER ENVIRONMENT LOCATED IN MILAN AND A SECONDARY BACKUP/DISASTER RECOVERY SITE LOCATED IN ROME. ENCRYPTION IN TRANSIT IS ENSURED THROUGH HTTPS/TLS 1.2 OR HIGHER FOR ALL COMMUNICATIONS, INCLUDING API CALLS TO AI PROVIDERS AND WEB-BASED ACCESS TO NOLOOP SYSTEMS. BACKUPS ARE MANAGED THROUGH VEEAM BACKUP SOFTWARE WITH ENCRYPTION AND IMMUTABILITY FEATURES, CONSISTENTLY WITH THE CONTROLS DESCRIBED IN THE BUSINESS CONTINUITY AND CRYPTOGRAPHY SECTIONS.

ACCESS TO SYSTEMS AND DATA PROCESSED BY AI IS RESTRICTED TO AUTHORIZED PERSONNEL BASED ON ROLES AND OPERATIONAL NEED, ACCORDING TO NOLOOP ACCESS MANAGEMENT AND INFORMATION SECURITY PROCEDURES UNDER THE ISO/IEC 27001:2022 CERTIFIED INFORMATION SECURITY MANAGEMENT SYSTEM."""
)

# R205 — Processes applied to AI
answers[205] = (
    "Yes",
    """THE FOLLOWING PROCESSES AND PROCEDURES ARE APPLIED ALSO TO AI SYSTEMS WITHIN THE PERIMETER OF NOLOOP'S INTEGRATED MANAGEMENT SYSTEM AND ISO/IEC 27001:2022 CERTIFIED INFORMATION SECURITY MANAGEMENT SYSTEM:

A) INITIAL RISK ANALYSIS OF AI SYSTEMS PROVIDED: AI SYSTEMS ARE SUBJECT TO RISK ASSESSMENT AS PART OF THE INFORMATION SECURITY MANAGEMENT SYSTEM AND THE R71 REGISTER OF AUTHORIZED ARTIFICIAL INTELLIGENCE SOLUTIONS. EACH AUTHORIZED AI SOLUTION IS CLASSIFIED ACCORDING TO EU AI ACT RISK CATEGORIES (CURRENTLY LIMITED-RISK FOR AUTHORIZED SOLUTIONS), WITH CONTROLS PROPORTIONAL TO THE IDENTIFIED RISK, INCLUDING TECHNICAL VALIDATION AND DPO/PRIVACY EVALUATION WHERE APPLICABLE.

B) SECURITY AND MANAGEMENT OF NETWORK: AI SYSTEMS OPERATE WITHIN THE NOLOOP NETWORK AND INFRASTRUCTURE PERIMETER, SUBJECT TO THE SAME NETWORK SECURITY CONTROLS, FIREWALL RULES, SEGREGATION AND ACCESS MANAGEMENT APPLIED TO ALL INTERNAL SYSTEMS, AS DESCRIBED IN THE RELEVANT SECTIONS OF THIS ASSESSMENT.

C) MANAGEMENT OF LOGGING AND MONITORING: AI SYSTEM USAGE IS LOGGED AT APPLICATION LEVEL ON NOLOOP INFRASTRUCTURE, IN ACCORDANCE WITH THE LOGGING AND MONITORING CONTROLS DESCRIBED IN THIS ASSESSMENT. ACCESS AND USE EVENTS ARE AVAILABLE FOR AUDIT.

D) METHODS TO ENHANCE TRANSPARENCY AND AUDITABILITY OF AI SYSTEMS: HUMAN SUPERVISION IS REQUIRED FOR ALL AI OUTPUTS USED IN OPERATIONAL PROCESSES. AI OUTPUTS ARE NOT USED AS THE SOLE BASIS FOR AUTOMATED DECISIONS PRODUCING LEGAL OR SIMILARLY SIGNIFICANT EFFECTS ON DATA SUBJECTS. RECORDS OF AI USAGE AND SYSTEM OUTPUTS ARE MAINTAINED AT APPLICATION LEVEL FOR AUDIT PURPOSES.

E) INCIDENT MANAGEMENT PROCEDURES AND PROCESSES: SECURITY INCIDENTS INVOLVING AI SYSTEMS ARE MANAGED ACCORDING TO NOLOOP SECURITY INCIDENT MANAGEMENT AND DATA BREACH MANAGEMENT PROCEDURES, AS DESCRIBED IN THE SECURITY INCIDENT MANAGEMENT, E-DISCOVERY & CLOUD FORENSICS SECTION OF THIS ASSESSMENT, INCLUDING THE COMMITMENT TO NOTIFY PIRELLI WITHIN 24 SOLAR HOURS FROM DETECTION OF RELEVANT INCIDENTS, FOR THE DURATION OF THE RETENTION/PROCESSING OF PIRELLI DATA BY NOLOOP."""
)

# Load the workbook
wb = openpyxl.load_workbook(SRC)
ws = wb['TIER 2 CLOUD']

# Reference formatting from an existing answered cell (row 155 per example)
ref_d = ws['D155']
ref_e = ws['E155']

ref_d_font = copy(ref_d.font)
ref_d_fill = copy(ref_d.fill)
ref_d_border = copy(ref_d.border)
ref_d_align = copy(ref_d.alignment)

ref_e_font = copy(ref_e.font)
ref_e_fill = copy(ref_e.fill)
ref_e_border = copy(ref_e.border)
ref_e_align = copy(ref_e.alignment)

# Write answers
for row_num, (answer, description) in answers.items():
    # Column D - answer
    cell_d = ws.cell(row=row_num, column=4)
    cell_d.value = answer
    cell_d.font = copy(ref_d_font)
    cell_d.fill = copy(ref_d_fill)
    cell_d.border = copy(ref_d_border)
    cell_d.alignment = Alignment(
        horizontal='center',
        vertical='center',
        wrap_text=True
    )
    
    # Column E - description
    cell_e = ws.cell(row=row_num, column=5)
    cell_e.value = description
    cell_e.font = copy(ref_e_font)
    cell_e.fill = copy(ref_e_fill)
    cell_e.border = copy(ref_e_border)
    cell_e.alignment = Alignment(
        horizontal='left',
        vertical='top',
        wrap_text=True
    )
    
    # Adjust row height for longer descriptions
    approx_lines = description.count('\n') + (len(description) // 120)
    ws.row_dimensions[row_num].height = max(60, min(approx_lines * 15, 500))

wb.save(OUT)
print(f"File salvato: {OUT}")

# Verify
wb_check = openpyxl.load_workbook(OUT, data_only=True)
ws_check = wb_check['TIER 2 CLOUD']
for r in [198, 199, 200, 201, 202, 203, 204, 205]:
    a = ws_check.cell(row=r, column=4).value
    d = ws_check.cell(row=r, column=5).value
    print(f"R{r}: Answer='{a}' | Desc length={len(d) if d else 0} chars")